// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB926QhhFDqw7MgRNS_Fx0827qMHZKfeZw',
    appId: '1:995246260968:web:51a2563abb7f2e0d413f5d',
    messagingSenderId: '995246260968',
    projectId: 'safe-harbor-db2cd',
    authDomain: 'safe-harbor-db2cd.firebaseapp.com',
    storageBucket: 'safe-harbor-db2cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtf3BI9Gc8jwG1EvoSwyNVxYszu5cmNc',
    appId: '1:995246260968:android:9a81c9347e38fa6d413f5d',
    messagingSenderId: '995246260968',
    projectId: 'safe-harbor-db2cd',
    storageBucket: 'safe-harbor-db2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JDgEK_qM5UKFr1rff1wMFNF3S-ilLzA',
    appId: '1:995246260968:ios:367be41d70874022413f5d',
    messagingSenderId: '995246260968',
    projectId: 'safe-harbor-db2cd',
    storageBucket: 'safe-harbor-db2cd.firebasestorage.app',
    iosBundleId: 'com.safeharbor.app',
  );

}